### ISSUE TITLE
Add support for hostAlias

### ISSUE THREAD

**Issue by hoeghh** [Praqma/jira-server#5]
In the file jira/templates/deployment.yaml we need to be able to define some hosts entries

eg. 
```
    spec:
      hostAliases:
      - ip: "192.168.50.4"
        hostnames:
        - "jira.example.com"
```
and then define the ip and hostname in the helm chart.
