### ISSUE TITLE
Support data center

### ISSUE THREAD

**Issue by hoeghh** [Praqma/jira-server#6]
To get data center to work, we need to create a file called cluster.properties

Heres a sample from ASK's docker-entrypoint.sh

```
# Setting cluster node name. These variables are exported in the jira-deployment.yaml file.
if [ ENABLE_DATACENTER_MODE = true ]; then
  cat <<EOF > $JIRA_HOME/cluster.properties
# This ID must be unique across the cluster.
jira.node.id = $JIRA_POD_NAME.jira.$JIRA_NAMESPACE.svc.cluster.local
# The location of the shared home directory for all JIRA nodes
jira.shared.home = /var/atlassian/jira-datacenter/
# Apparently this might need to be set to get the cache synchronization work
ehcache.listener.hostName = $JIRA_POD_NAME.jira.$JIRA_NAMESPACE.svc.cluster.local
ehcache.listener.port = 40001
ehcache.object.port = 40011
EOF
fi
```
Also, we need a add a volume.

In Ask we place the extra volume in /var/atlassian/jira-datacenter/ via  :
```
          volumeMounts:
            - name: "jira-home"
              mountPath: /var/atlassian/application-data/jira/
            - name: "jira-datacenter"
              mountPath: /var/atlassian/jira-datacenter/
```

And get the two environment variables : 
```
          env:
          - name: JIRA_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: JIRA_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```
