### ISSUE TITLE
Use a selector on the PersistantVolumeClaimTemplate

### ISSUE THREAD

**Issue by hoeghh** [Praqma/jira-server#7]
If you have 5 PV that meet the criterias by Jira, it will just pick one randomly.

We need a selector in the template, and be able to define labels so that we can target the volumeclaim to a specific group of pv(s).

This will be payed by Vestas

Like this example
```
  volumeClaimTemplates:
    - metadata:
        name: html
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        selector:
          matchLabels:
            foo: foo
            bar: bar
```
